# Generated by Django 2.2.9 on 2020-01-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
