# Generated by Django 2.2.9 on 2020-01-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0002_auto_20200124_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
